name: product

networks:
  product-network:
    driver: bridge

services:
  # mysql
  mysql:
    image: mysql:latest
    container_name: product_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
      TZ: Asia/Seoul
    ports:
      - "3667:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      product-network:
        aliases:
          - mysql